version: '3.1'

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - featurehub-ps-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  party-server:
    image: featurehub/party-server:latest
    user: 999:999
    restart: always
    environment:
      - db.url=jdbc:postgresql://db:5432/featurehub
      - db.username=featurehub
      - db.password=featurehub
      - jersey.cors.headers=X-Requested-With,Authorization,Content-type,Accept-Version,Content-MD5,CSRF-Token,x-ijt,cache-control,x-featurehub,Baggage
    ports:
      - 8085:8085
    depends_on:
      - "db"
volumes:
  featurehub-ps-db:
